# Generated by Django 4.1.7 on 2023-03-03 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("instructions", models.TextField(help_text="*learning objectives*")),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_test",
                        to="courses.lessonmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.IntegerField(default=0)),
                ("text", models.CharField(max_length=1000)),
                (
                    "lecture",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="assessments.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("Multiplechoice", "Multiplechoice"),
                            ("Long Answer", "Long Answer"),
                            ("Short Answer", "Short Answer"),
                        ],
                        default="Short Answer",
                        max_length=20,
                    ),
                ),
                ("answer_text", models.CharField(blank=True, max_length=1000)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.qestionmodel",
                    ),
                ),
                (
                    "student_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
