# Generated by Django 4.1.7 on 2023-03-03 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answermodel",
            name="student_user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
