# Generated by Django 4.1.7 on 2023-03-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_answermodel_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answermodel",
            name="qtype",
        ),
    ]
