# Generated by Django 4.1.7 on 2023-03-04 09:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0005_alter_answermodel_answer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="answermodel",
            name="timestamp",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answermodel",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="qestionmodel",
            name="timestamp",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="qestionmodel",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="period",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.RemoveField(
            model_name="answermodel",
            name="student_user",
        ),
        migrations.CreateModel(
            name="ScoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.CharField(default=None, max_length=10000)),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_assess",
                        to="assessments.quiz",
                    ),
                ),
                (
                    "stdnt_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answermodel",
            name="student_user",
            field=models.ManyToManyField(
                default=None, related_name="student_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
