# Generated by Django 4.1.7 on 2023-02-28 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coverImg", models.ImageField(upload_to="course_categrogy/")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(default=None)),
                (
                    "maker",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coverImg", models.ImageField(upload_to="courses/")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("cost", models.CharField(max_length=120)),
                ("duration", models.CharField(max_length=120)),
                ("skillLevel", models.CharField(max_length=120)),
                ("requirements", models.CharField(max_length=120)),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(default=None)),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="courses.coursecategorymodel",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(help_text="*Benefits*")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("expires", models.CharField(help_text="1 month", max_length=1000)),
                ("is_published", models.BooleanField(default=False)),
                ("slug", models.SlugField(default=None)),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "_course",
                    models.ManyToManyField(
                        related_name="_course", to="courses.coursemodel"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscriptionPackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack",
                        to="courses.packmodel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coverImg", models.ImageField(upload_to="courses/")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(help_text="*learning objectives*")),
                ("progress", models.IntegerField(verbose_name="progress level")),
                (
                    "bookmark",
                    models.BooleanField(default=False, verbose_name="Bookmark"),
                ),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "video_link",
                    models.TextField(
                        blank=True, default=None, verbose_name="video link"
                    ),
                ),
                ("main_content", models.TextField(help_text="*learning objectives*")),
                ("is_published", models.BooleanField(default=False)),
                ("slug", models.SlugField(default=None)),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course",
                        to="courses.coursemodel",
                    ),
                ),
            ],
        ),
    ]
