# Generated by Django 4.1.7 on 2023-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_coursemodel_category_alter_lessonmodel_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategorymodel",
            name="slug",
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name="coursemodel",
            name="slug",
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name="lessonmodel",
            name="slug",
            field=models.SlugField(default=None),
        ),
    ]
