# Generated by Django 4.1.7 on 2023-03-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("assessments", "0003_alter_answermodel_student_user"),
        ("tracker", "0002_delete_lessonweekmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonWeekModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(default=1)),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courser_outline",
                        to="courses.lessonmodel",
                    ),
                ),
                (
                    "test",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="tester",
                        to="assessments.quiz",
                    ),
                ),
            ],
        ),
    ]
